version: '3.7'
services:
  book-finder:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    container_name: postgres
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./backend/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./backend/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: ./servers/app/Dockerfile
    volumes:
      - '.:/backend'
      - '/backend/node_modules'
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: ./servers/auth/Dockerfile
    volumes:
      - '.:/backend'
      - '/backend/node_modules'
    ports:
      - 4001:4001
    environment:
      - CHOKIDAR_USEPOLLING=true
