version: '3.7'
services:
  book-finder:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    container_name: db
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book-finder
    ports:
      - '5432:5432'
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: app
    build:
      context: ./backend
      dockerfile: ./servers/app/Dockerfile
    volumes:
      - '.:/backend'
      - '/backend/node_modules'
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true

  auth:
    container_name: auth
    build:
      context: ./backend
      dockerfile: ./servers/auth/Dockerfile
    volumes:
      - '.:/backend'
      - '/backend/node_modules'
    ports:
      - 4001:4001
    environment:
      - CHOKIDAR_USEPOLLING=true
